int checkTierra() {
  contadorChequearTierra = 0;
  int promedioSensoresTierraHumedad = sensarHumMacetas();
  Serial.println(promedioSensoresTierraHumedad);

  if(promedioSensoresTierraHumedad < 999){

    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    delay(3000);
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    delay(3000);
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    delay(3000);
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    delay(3000);
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    delay(3000);
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    delay(3000);
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    delay(3000);
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    Serial.println("MIRAME MARGE; ESTOY REGANDO");
    delay(3000);
    
    
  }
  
  return sensarHumMacetas;
}
